# -*- coding: utf-8 -*-
"""app

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Px9xcGmtOD75gnr8vpeuFwnChG-K4Njq
"""

from ast import Return

import numpy as np
from tensorflow.keras.models import load_model

from flask import Flask, render_template, request

app = Flask(__name__)
model = load_model(r'C:\Users\sreen\Desktop\Home page\Flask\crude_oil.h5')

@app.route('/')
def home() :
  return render_template('index.html')

@app.route('/about')
def about() :
  return render_template("index.html")

@app.route('/predict')
def predict() :
  return render_template("web.html")

@app.route('/login',methods = ['POST', 'GET']) 
def login():
  x_input=float(request.form['year'])
  x_input=x_input.split(',')
  print(x_input)
  for i in range(0, len(x_input)):
      x_input[i] = float(x_input[i])
  print(x_input)
  x_input=np.array(x_input).reshape(1,-1)
  temp_input=list(x_input)
  temp_input=temp_input[0].tolist()
  firstoutput = []
  n_steps=10
  i=0
  while (i<1):
    
    if(len(temp_input)>10):
      x_input=np.array(temp_input[1:]) 
      print("{} day input {}".format(i,x_input))
      x_input=x_input.reshape(1,-1)
      x_input.reshape((1, n_steps, 1)) 
      yhat = model.predict(x_input, verbose=0)
      print("{} day output {}".format(i,yhat)) 
      temp_input.extend(yhat[0].tolist())
      temp_input=temp_input[1:]
      firstoutput.extend(yhat.tolist())
      i=i+1

    else:
      x_input = x_input.reshape((1, n_steps,1))
      yhat = model.predict(x_input, verbose=0) 
      print(yhat[0])
      temp_input.extend(yhat[0].tolist())
      print(len(temp_input))
      firstoutput.extend(yhat.tolist())
      i=i+1
  print(firstoutput)
  return render_template("web.html",showcase = 'The next day predicted value is:'+float(firstoutput))




if __name__=='__main__': 
  app.run(debug=True, port=5000)